### ISSUE TITLE
杀毒软件会屏蔽跨域访问请求

### ISSUE THREAD

**Issue by xb191799981** [aspnet/AspNetCore.Docs.zh-cn#193]
1、我安装了最新版本的卡巴斯基安全软件，当启动它之后， SignalR的跨域访问会被自动截断，请问有什么办法来解决吗？   当关闭卡巴斯基后客户端才能正常连接到服务端。

2、我在家自己的电脑上搭建了站点， 然后使用内网映射工具(Nat123)做了一个动态域名解析和端口映射，, 因为所有请求都是通过工具中转访问， 所以SignalR总是会映射到工具(Nat123)的CDN服务里面，提示映射错误 。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [启用 ASP.NET Core 中的跨域请求 (CORS)](https://docs.microsoft.com/zh-cn/aspnet/core/security/cors?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/cors.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @xb191799981
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@xb191799981
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
1. I installed the latest version of Kaspersky Security. After launching it, SignalR's cross-domain access will be automatically truncated. Is there any way to solve it? The client can connect to the server normally when Kaspersky is closed.

Disable Kaspersky 
禁用卡巴斯基


2. I built a site on my own computer, and then used the intranet mapping tool (Nat123) to do a dynamic domain name resolution and port mapping. Because all requests are accessed through tools, SignalR always maps to the tool. (Nat123) CDN service, prompt mapping error.
