### ISSUE TITLE
I found that the two pages were written incorrectly.

### ISSUE THREAD

**Issue by userQin159** [aspnet/AspNetCore.Docs.zh-cn#219]
open link 1、
https://docs.microsoft.com/zh-cn/aspnet/core/data/ef-mvc/complex-data-model?view=aspnetcore-3.0#the-required-attribute 
 
**You could remove the Required attribute and replace it with a minimum length parameter for the StringLength attribute:**
--------------------
open link 2、
https://docs.microsoft.com/zh-cn/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-3.0&tabs=visual-studio#the-required-attribute
 
**The Required attribute must be used with MinimumLength for the MinimumLength to be enforced.**

**Comment by srvbpigh** [comment]
Hello, @userQin159
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore.Docs #15790](https://github.com/aspnet/AspNetCore.Docs/issues/15790) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @userQin159 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/15790

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
