### ISSUE TITLE
Command update-database failed

### ISSUE THREAD

**Issue by PanQiWei** [aspnet/AspNetCore.Docs.zh-cn#222]
After excute Add-Migration InitialCreate correctly,the command Update-Database failed with the following error:
Error Number:5123,State:1,Class:16
CREATE FILE encountered operating system error 5(拒绝访问。) while attempting to open or create the physical file 'C:\Users\59455RazorPagesMovieContext-b2dc6870-9632-49c3-a351-68dc42444044.mdf'.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
Can masters help me!!!

**Comment by PanQiWei** [comment]
Is that I need to redirect the folder path to create the database?

**Comment by PanQiWei** [comment]
It seems there is no web.config file for me to redirect path...

**Comment by srvbpigh** [comment]
Hello, @PanQiWei
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore.Docs #15946](https://github.com/aspnet/AspNetCore.Docs/issues/15946) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @PanQiWei

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/15946

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
