### ISSUE TITLE
Aren't WebHostBuilder used in .net core 3.1?

### ISSUE THREAD

**Issue by JingLi-kooboo** [aspnet/AspNetCore.Docs.zh-cn#239]
Aren't WebHostBuilder used in .net core 3.1? Don't you need to replace it with IHostBuilder？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [ASP.NET Core 中的集成测试](https://docs.microsoft.com/zh-cn/aspnet/core/test/integration-tests?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @JingLi-kooboo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore.Docs #16584](https://github.com/aspnet/AspNetCore.Docs/issues/16584) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @JingLi-kooboo, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/16584. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
